### ISSUE TITLE
Add "include(FetchContent)"-line to README.md

### ISSUE THREAD

**Issue by niekbouman** [robinlinden/libsodium-cmake#9]
Dear Rob,

Thank you for contributing this repo. For me it is extremely useful!
Just one little note, under the "Using in your project" part of the README.md, you could add
```
   include(FetchContent)
```
which could help users unfamiliar with CMake's FetchContent machinery (like myself, before coming across your repo..!)

kind regards,
Niek

**Comment by robinlinden** [comment]
Sure thing! It would be good if the example were self-contained, including the minimum_version, I suppose. :)

I'm happy to hear you think the project is useful!
